language: python
dist: bionic
python: 3.6
sudo: true
services:
  - docker
install: skip
jobs:
  include:
    - stage: security
      before_script:
        - sudo make install-vulnerabilities-checker
      script:
        - make check-vulnerabilities
    - stage: unit tests
      before_script:
        - make install-docker-packer
        - make install-docker-packer-tests
      script:
        - make test-docker-packer
    - stage: docker builds
      script:
        - make docker-build-docker-packager
    - stage: lint
      before_script:
        - make install-docker-packer
        - make install-docker-packer-tests
      script:
        - make lint-docker-packer
