kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-resources"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "fluentd" "root" .) | nindent 4 }}
data:
  resources.yaml: |
    {{ if .Values.packagers.cli.enabled -}}
    kind: PackagingIntegration
    id: docker-cli
    spec:
      entrypoint: "/usr/local/bin/odahu-flow-pack-to-cli"
      defaultImage: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.packagers.cli "tpl" "%sodahu-flow-packagers:%s") }}"
      privileged: true
      schema:
        targets:
          - name: docker-push
            connectionTypes: ["docker", "ecr"]
            default: "{{ .Values.packagers.cli.targets.docker_push.default }}"
            required: true
          - name: docker-pull
            connectionTypes: ["docker", "ecr"]
            default: "{{ .Values.packagers.cli.targets.docker_pull.default }}"
            required: false
        arguments:
          properties:
            - name: dockerfileBaseImage
              parameters:
                - name: description
                  value: Base image for Dockerfile.
                - name: type
                  value: string
                - name: default
                  value: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.packagers.base "tpl" "%sodahu-flow-docker-packager-base:%s") }}"
            - name: imageName
              parameters:
                - name: description
                  value: |
                    {{`This option provides a way to specify the Docker image name. You can hardcode the full name or specify a template. Available template values:
                      - Name (Model Name)
                      - Version (Model Version)
                      - RandomUUID
                    The default value is '{{ Name }}/{{ Version }}:{{ RandomUUID }}'.
                    Image name examples:
                      - myservice:123
                      - {{ Name }}:{{ Version }}`}}
                - name: type
                  value: string
                - name: default
                  value: "{{`{{ Name }}-{{ Version }}:{{ RandomUUID }}`}}"
    {{- end -}}
    {{- if .Values.packagers.rest.enabled }}
    ---
    kind: PackagingIntegration
    id: docker-rest
    spec:
      entrypoint: "/usr/local/bin/odahu-flow-pack-to-rest"
      defaultImage: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.packagers.rest "tpl" "%sodahu-flow-packagers:%s") }}"
      privileged: true
      schema:
        targets:
          - name: docker-push
            connectionTypes: ["docker", "ecr"]
            default: "{{ .Values.packagers.rest.targets.docker_push.default }}"
            required: true
          - name: docker-pull
            connectionTypes: ["docker", "ecr"]
            default: "{{ .Values.packagers.rest.targets.docker_pull.default }}"
            required: false
        arguments:
          properties:
            - name: dockerfileBaseImage
              parameters:
                - name: description
                  value: Base image for Dockerfile.
                - name: type
                  value: string
                - name: default
                  value: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.packagers.base "tpl" "%sodahu-flow-docker-packager-base:%s") }}"
            - name: host
              parameters:
                - name: description
                  value: Host to bind.
                - name: type
                  value: string
                - name: default
                  value: 0.0.0.0
            - name: port
              parameters:
                - name: description
                  value: Port to bind.
                - name: type
                  value: integer
                - name: default
                  value: 5000
            - name: timeout
              parameters:
                - name: description
                  value: Serving timeout in seconds.
                - name: type
                  value: integer
                - name: default
                  value: 60
            - name: workers
              parameters:
                - name: description
                  value: Count of serving workers.
                - name: type
                  value: integer
                - name: default
                  value: 1
            - name: threads
              parameters:
                - name: description
                  value: Count of serving threads.
                - name: type
                  value: integer
                - name: default
                  value: 4
            - name: imageName
              parameters:
                - name: description
                  value: |
                    {{`This option provides a way to specify the Docker image name. You can hardcode the full name or specify a template. Available template values:
                      - Name (Model Name)
                      - Version (Model Version)
                      - RandomUUID
                    The default value is '{{ Name }}/{{ Version }}:{{ RandomUUID }}'.
                    Image name examples:
                      - myservice:123
                      - {{ Name }}:{{ Version }}`}}
                - name: type
                  value: string
                - name: default
                  value: "{{`{{ Name }}-{{ Version }}:{{ RandomUUID }}`}}"
    {{- end -}}
    {{- if .Values.packagers.triton.enabled }}
    ---
    kind: PackagingIntegration
    id: docker-triton
    spec:
      entrypoint: "/usr/local/bin/odahu-flow-pack-to-triton"
      defaultImage: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.packagers.rest "tpl" "%sodahu-flow-packagers:%s") }}"
      privileged: true
      schema:
        targets:
          - name: docker-push
            connectionTypes: ["docker", "ecr"]
            default: "{{ .Values.packagers.triton.targets.docker_push.default }}"
            required: true
        arguments:
          properties:
            - name: triton_base_image_tag
              parameters:
                - name: description
                  value: Triton base image tag for Dockerfile.
                - name: type
                  value: string
                - name: default
                  value: "{{ .Values.packagers.triton.default_triton_base_image_tag }}"
            - name: imageName
              parameters:
                - name: description
                  value: |
                    {{`This option provides a way to specify the Docker image name. You can hardcode the full name or specify a template. Available template values:
                      - Name (Model Name)
                      - Version (Model Version)
                      - RandomUUID
                    The default value is '{{ Name }}/{{ Version }}:{{ RandomUUID }}'.
                    Image name examples:
                      - myservice:123
                      - {{ Name }}:{{ Version }}`}}
                - name: type
                  value: string
                - name: default
                  value: "{{`{{ Name }}-{{ Version }}:{{ RandomUUID }}`}}"
    {{- end }}
---
{{- if or (eq .Values.packagers.rest.enabled true) (eq .Values.packagers.cli.enabled true)}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-packager-resources-uploader"
  labels:
    component: "packager-resources-uploader"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: resources
          configMap:
            name: "{{ .Release.Name }}-resources"
      containers:
        - name: packager-resources-uploader
          env:
            - name: API_URL
              value: {{ .Values.apiUrl }}
          image: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.odahuflowctl "tpl" "%sodahu-flow-cli:%s") }}"
          volumeMounts:
            - mountPath: /opt/odahu-flow-resources
              name: resources
          command:
            - /bin/sh
            - -c
          args: ["
          {{- if .Values.security.mesh_authn -}}
            odahuflowctl login
          --client_id {{ .Values.resource_uploader_sa.client_id }}
          --client_secret {{ .Values.resource_uploader_sa.client_secret }}
          --issuer {{ .Values.oauth_oidc_issuer_url }}
          --url {{ .Values.apiUrl }}
          && {{ end -}}
          odahuflowctl bulk apply /opt/odahu-flow-resources/resources.yaml"]
{{- end}}