version: 2.1

jobs:
  security-check:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo make install-vulnerabilities-checker
      - run: make check-vulnerabilities
  lint-n-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            make install-docker-packer
            make install-docker-packer-tests
      - run:
          name: Lint
          command: make lint-docker-packer
      - run:
          name: Test
          command: make test-docker-packer
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build
          command: make docker-build-docker-packager

workflows:
  main:
    jobs:
      - security-check
      - lint-n-test:
          requires:
            - security-check
      - build:
          requires:
            - lint-n-test
