# Docker images registry
# This registry will be used for automatic docker image name deduction based on Legion naming for images
# Each image could be overridden manually in .<service>.image, please see .edi root section or other
# Type: string
imagesRegistry: odahu/

# Version of Toolchain
# By default .Chart.AppVersion version is used
# Type: string
# packagerVersion: "1.0"

# Resource applier configuration
resources_applier:
  # This variable can be uncommented to setup custom image name
  # Type: string
  # image: custom-image:1.0

packagers:
  rest:
    # REST packager could be disabled
    # Type: bool
    enabled: true

    # This variable can be uncommented to setup custom image name for REST packager
    # Type: string
    # image: custom-image:1.0

  cli:
    enabled: true
