FROM nvcr.io/nvidia/tritonserver:{{ triton_base_image_tag }}

EXPOSE 8000/tcp
EXPOSE 8001/tcp
EXPOSE 8002/tcp

ENV MODEL_REPO "/models_repository"

COPY . ${MODEL_REPO}

{% if conda_file_path %}
# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p /root/miniconda3
ENV PATH $PATH:/root/miniconda3/bin

# Create Conda env and install dependencies
RUN conda init bash && \
    source $HOME/.bashrc && \
    conda env create -f ${MODEL_REPO}/conda.yaml -n triton
{% set backend_arg = '--backend-config=python,python-runtime=/root/miniconda3/envs/triton/bin/python' %}

{% else %}
{% set backend_arg = '' %}

{% endif %}

CMD tritonserver --log-verbose 100 --strict-model-config=false --model-repository=/models_repository {{ backend_arg }}
